/**
 * 
 */
package com.chordLyric.api.models.impl;

import javax.annotation.Generated;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.validator.constraints.NotEmpty;

import com.chordLyric.api.models.types.ArtistType;
import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * @author Yogen
 *
 */
@Getter
@Setter
@ToString
@Entity
public class Artist extends Article {
	
	@Id
//	@GeneratedValue(strategy = GenerationType.AUTO)
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid2")
	private String id;

	@NotNull
	@NotEmpty
	private String name;
	
	private String bio;

	@NotNull
	@Enumerated(EnumType.STRING)
	private ArtistType type;
	
	/*@JsonIgnore
	@Id
	@DynamoDBHashKey (attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@NotNull
	@NotEmpty
	@DynamoDBAttribute(attributeName = "Role")
	private String name;
	
	@DynamoDBAttribute(attributeName = "Bio")
	private String bio;

	@NotNull
	@DynamoDBTyped(DynamoDBAttributeType.S)
	@DynamoDBAttribute(attributeName = "Type")
	private ArtistType type;*/
}
