/**
 * 
 */
package com.chordLyric.api.models.impl;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.chordLyric.api.models.types.ArtistType;
import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * @author Yogen
 *
 */
@Getter
@Setter
@ToString
@DynamoDBDocument
public class Artist extends Article {
	
	@JsonIgnore
	@Id
	@DynamoDBHashKey (attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@NotNull
	@NotEmpty
	@DynamoDBAttribute(attributeName = "Role")
	private String name;
	
	@DynamoDBAttribute(attributeName = "Bio")
	private String bio;

	@NotNull
	@DynamoDBTyped(DynamoDBAttributeType.S)
	@DynamoDBAttribute(attributeName = "Type")
	private ArtistType type;
}
