server:
  port: 8083
  
api:
  build:
    version: 0.0.1
    
amazon:
  dynamodb:
    endpoint: http://localhost:8000/


logging:
  level: 
    org.springframework.security: DEBUG

spring:
  data:
    elasticsearch:
      cluster-nodes: search-inventory-rp3oetro645lbitr56th2sntke.us-east-1.es.amazonaws.com:9300 #localhost:9200